### ISSUE TITLE
Why is the parameter θ in Formula 3 not followed by a sigmoid?

### ISSUE THREAD

**Issue by xuezhongcailian** [PbGuo/QueryCDR#2]
![image](https://github.com/user-attachments/assets/197df249-d166-4af6-a0f9-019757534ebb)

**Comment by PbGuo** [comment]
For the code implementation, we use Softmax to predict the coefficient.

**Comment by xuezhongcailian** [comment]
However, it seems that this is not mentioned in the paper.

**Comment by PbGuo** [comment]
Yes, we omitted this detail in our paper.
